### ISSUE TITLE
DataGrid with sticky columns , row data is not sticky

### ISSUE THREAD

**Issue by kunwarkds** [carbon-design-system/ibm-products#5558]
### Package

Carbon for IBM Products

### Description

When a DataGrid column is made sticky , the row data does not gets sticked after few columns when using useInfiniteScroll to the left/right but the header is sticky.

### Component(s) impacted

Datagrid

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.43.1",

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Data visualization 

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/github/kunwarkds/stickycolumn/main?import=true

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Hi @kunwarkds, this was resolved [here](https://github.com/carbon-design-system/ibm-products/pull/5461) and included in [@carbon/ibm-products@2.43.0](https://github.com/carbon-design-system/ibm-products/releases/tag/%40carbon%2Fibm-products%402.43.0).

The code sandbox you provided is using `2.21.0`, upgrading should resolve the issue.

**Comment by kunwarkds** [comment]
@matthewgallo 
Verified with 2.43.0 earlier however could not updated in sandbox
Issue still exist with 2.43.0 version 
code sandbox updated with 2.43.0 now
https://codesandbox.io/p/github/kunwarkds/stickycolumn/main?import=true
Please reopen this issue
